### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/broccoli-eyeglass#8]
Error:

```
Cannot read property 'on' of undefined
TypeError: Cannot read property 'on' of undefined
   at CoreObject.BroccoliSassCompiler.extend.init (/Users/bar/Code/foo/node_modules/broccoli-eyeglass/lib/index.js:23:16)
    at CoreObject.init (/Users/bar/Code/foo/node_modules/broccoli-caching-writer/node_modules/core-object/lib/assign-properties.js:18:18)
    at CoreObject.Class (/Users/bar/Code/foo/node_modules/broccoli-caching-writer/node_modules/core-object/core-object.js:32:38)
...
```

Looked similar to #4 but I checked that we are using the `new` operator for BroccoliEyeglass.

```js
var BroccoliEyeglass = require('broccoli-eyeglass');
```

`    "broccoli-eyeglass": "1.0.2",`

Will try an upgrade :)

**Comment by alanhogan** [comment]
Good news — updating to 1.1.1, and also bumping broccoli-caching-writer to 1.0.0, running `npm install` (and, in my project, a `bower install`) cleared this issue.
