### ISSUE TITLE
What’s wrong with this tiny example project? (undefined is not a function at cleanupTree)

### ISSUE THREAD

**Issue by alanhogan** [sass-eyeglass/broccoli-eyeglass#9]
Hi,

I started writing some examples for the project's README and decided it would be best to make sure all the examples really worked :wink: so I made a little sample project called `example-1` and ran `broccoli build dist` in it, expecting two tiny `.css` files to come out of it; instead, I got the following error.

```
Repos/broccoli-eyeglass[examples]% cd examples/example-1                      
examples/example-1[examples]% broccoli build dist
TypeError: undefined is not a function
    at cleanupTree (/Users/ahogan/Repos/broccoli-eyeglass/node_modules/broccoli/lib/builder.js:128:19)
    at /Users/ahogan/Repos/broccoli-eyeglass/node_modules/broccoli/node_modules/promise-map-series/index.js:11:14
    at lib$rsvp$$internal$$tryCatch (/Users/ahogan/Repos/broccoli-eyeglass/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/ahogan/Repos/broccoli-eyeglass/node_modules/rsvp/dist/rsvp.js:505:17)
    at /Users/ahogan/Repos/broccoli-eyeglass/node_modules/rsvp/dist/rsvp.js:1001:13
    at lib$rsvp$asap$$flush (/Users/ahogan/Repos/broccoli-eyeglass/node_modules/rsvp/dist/rsvp.js:1198:9)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Build failed
examples/example-1[examples]% 
```

Any ideas?

Take a look at my mini example project here: https://github.com/alanhogan/broccoli-eyeglass/tree/examples/examples/example-1

Thanks :)

**Comment by alanhogan** [comment]
Gosh I’m dumb. I need a `module.exports = ` line for the Brocfile to work.
